from random import choice

aristotle_quotes = [
    'El hombre nada puede aprender sino en virtud de lo que sabe.',
    'No todo término merece el nombre de fin, sino tan sólo el que es óptimo.',
    'Las ciencias tienen las raíces amargas, pero muy dulces los frutos.',
    'Lo que con mucho trabajo se adquiere, más se ama.',
    'La naturaleza no hace nada en vano.',
    'La amistad es un alma que habita en dos cuerpos; un corazón que habita en dos almas.',
    'El hombre solitario es una bestia o un dios.',
    'Un amigo fiel es un alma en dos cuerpos.',
    'La verdadera felicidad consiste en hacer el bien.',
    'El entendimiento es una tabla lisa en la cual no hay nada escrito.',
    'Lo que con mucho trabajo se adquiere, más se ama.',
    'Piensa como piensan los sabios, mas habla como habla la gente sencilla.',
    'No se puede desatar un nudo sin saber cómo está hecho.',
    'Un amigo fiel es un alma en dos cuerpos.',
    'La finalidad del arte es dar cuerpo a la esencia secreta de las cosas, no el copiar su apariencia.',
    'Los que obran bien son los únicos que pueden aspirar en la vida a la felicidad.',
    'Nuestro carácter es el resultado de nuestra conducta.',
    'El alma es aquello por lo que vivimos, sentimos y pensamos.',
    'El amigo es otro yo. Sin amistad el hombre no puede ser feliz.',
    'La amistad perfecta es la de los buenos y de aquellos que se asemejan por la virtud.',
    'Los grandes conocimientos engendran las grandes dudas.',
    'Es de importancia para quien desee alcanzar una certeza en su investigación, el saber dudar a tiempo.',
    'La verdadera felicidad consiste en hacer el bien.',
    'El sabio no dice todo lo que piensa, pero siempre piensa todo lo que dice.',
    'El verdadero discípulo es el que supera al maestro.',
    'Algunos creen que para ser amigos basta con querer, como si para estar sano bastara con desear la salud.',
    'Se piensa que lo justo es lo igual, y así es; pero no para todos, sino para los iguales. Se piensa por el contrario que lo justo es lo desigual, y así es, pero no para todos, sino para los desiguales.',
    'Cualquiera puede enfadarse, eso es algo muy sencillo. Pero enfadarse con la persona adecuada, en el grado exacto, en el momento oportuno, con el propósito justo y del modo correcto, eso, ciertamente, no resulta tan sencillo.',
    'La esperanza es el sueño del hombre despierto.',
    'La virtud resplandece en las desgracias.',
    'En las adversidades sale a la luz la virtud.',
    'La amistad es un alma que habita en dos cuerpos; un corazón que habita en dos almas.',
    'Es propio del filósofo poder especular sobre todas las cosas.',
    'El aprendizaje no es un juego de niños; no podemos aprender sin sufrimiento.',
    'Nada hay en la mente que no haya estado antes en los sentidos.',
    'El ignorante afirma, el sabio duda y reflexiona.',
    'La inteligencia consiste no sólo en el conocimiento, sino también en la destreza de aplicar los conocimientos en la práctica.',
    'Es absolutamente imposible demostrarlo todo.',
    'Un estado es gobernado mejor por un hombre bueno que por unas buenas leyes.',
    'Si los ciudadanos practicasen entre sí la amistad, no tendrían necesidad de la justicia.',
    'Las enseñanzas orales deben acomodarse a los hábitos de los oyentes.',
    'La virtud es una disposición voluntaria adquirida, que consiste en un término medio entre dos extremos malos, el uno por exceso y el otro por defecto.',
    'Saber es acordarse.',
    'Es un principio indiscutible que para saber mandar bien, es preciso saber obedecer.',
    'No basta decir solamente la verdad, más conviene mostrar la causa de la falsedad.',
    'Adquirir desde jóvenes tales o cuales hábitos no tiene poca importancia: tiene una importancia absoluta.',
    'La Polis es una de las cosas que existen por naturaleza; y el hombre es, por naturaleza, un animal político.',
    'Gracias a la memoria se da en los hombres lo que se llama experiencia.',
    'Todo acto forzoso se vuelve desagradable.',
    'Avaro es el que no gasta en lo que debe, ni lo que debe, ni cuando debe.',
    'El tiempo es la medida del movimiento entre dos instantes.',
    'Nunca se alcanza totalmente la verdad, ni nunca se está totalmente alejado de ella.',
    'La ciencia es respecto del alma lo que es la luz respecto de los ojos, y si las raíces son amargas, los frutos son muy dulces.',
    'Es peor cometer una injusticia que sufrirla.',
    'En realidad vivir como hombre significa elegir un blanco -honor, gloria, riqueza, cultura- y apuntar hacia él con toda la conducta, pues no ordenar la vida a un fin es señal de gran necedad.',
    'El único Estado estable es aquel en que todos los ciudadanos son iguales ante la ley.',
    'El hombre nada puede aprender sino en virtud de lo que sabe.',
    'Es ignorancia no saber distinguir entre lo que necesita demostración y lo que no la necesita.',
    'En parte, el arte completa lo que la naturaleza no puede elaborar y, en parte, imita a la naturaleza.',
    'No se puede ser y no ser algo al mismo tiempo y bajo el mismo aspecto (Principio de no contradicción).',
    'La sabiduría es un adorno en la prosperidad y un refugio en la adversidad.',
    'Así como los ojos de los murciélagos se ofuscan a la luz del día, de la misma manera a la inteligencia de nuestra alma la ofuscan las cosas evidentes.',
    'Los discursos inspiran menos confianza que las acciones.',
    'Enseñar no es una función vital, porque no tienen el fin en sí misma; la función vital es aprender.',
    'El castigo del embustero es no ser creído, aun cuando diga la verdad.',
    'El que vive en soledad es una bestia o un dios.',
    'Considero más valiente al que conquista sus deseos, que al que conquista a sus enemigos, ya que la victoria más dura es la victoria sobre uno mismo.',
    'El amigo de todo el mundo no es un amigo.',
    'Sólo hay una fuerza motriz: el deseo.',
    'Una definición es una frase que significa la esencia de una cosa.',
    'La finalidad del arte es dar cuerpo a la esencia secreta de las cosas, no el copiar su apariencia.',
    'El que posee las nociones más exactas sobre las causas de las cosas y es capaz de dar perfecta cuenta de ellas en su enseñanza, es más sabio que todos los demás en cualquier otra ciencia.',
    'Se quiere más aquello que se ha conseguido con muchas fatigas.',
    'La Historia relata lo que sucedió; mientras que la Poesía trata sobre lo que debía suceder.',
    "Sólo hay felicidad donde hay virtud y esfuerzo serio, pues la vida no es un juego.",
    'Hay la misma diferencia entre un sabio y un ignorante que entre el vivo y el muerto.',
    'La mente siempre tiene razón, mientras que el apetito y la imaginación pueden equivocarse.',
    'Si nada hay eterno, no es posible la producción ni la generación.',
    'El movimiento no existe fuera de las cosas, pues todo lo que cambia, o cambia en el orden de la sustancia o en la cantidad, o en la calidad, o en el lugar.',
    'La riqueza consiste mucho más en el disfrute que en la posesión.',
    'Como la vista es al cuerpo, la razón es al espíritu.',
    'El miedo es un sufrimiento que produce la espera de un mal.',
    'Todo lo que se mueve es movido por otro.',
    'El hombre que se mantiene en el justo medio lleva el nombre de sobrio y moderado.',
    'El imitar es connatural al hombre.',
    'Todo hombre, por naturaleza, desea saber.',
    'Y es que la naturaleza no hace nada en vano, y entre los animales, el hombre es el único que posee la palabra.',
    'Platón es mi amigo, pero más amigo soy de la verdad.',
    'El mando de muchos no es bueno; basta un solo jefe.',
    'La democracia ha surgido de la idea de que sí los hombres son iguales en cualquier respecto, lo son en todos.',
    'Todos los gobiernos mueren por la exageración de su principio.',
    'Aprendemos, o por inducción o por demostración. La demostración parte de lo universal; la inducción de lo particular.',
    'Cuanto más nos inclina la naturaleza a los placeres, tanto más propensos somos a la licencia que a la decencia.',
    'El instante es la continuidad del tiempo, pues une el tiempo pasado con el tiempo futuro.',
    'Es necesario que haya uno o varios principios y aun, en caso de existir uno sólo, que éste sea inmóvil e inmutable.',
    'Fuera de la sociedad, el hombre es una bestia o un dios.',
    'Movimiento es el paso de la potencia al acto.',
    'Los predicados del predicado se extienden también al sujeto.',
    'La verdadera causa final reside en los seres inmóviles.',
    'La naturaleza no hace nada en vano.',
    'Quien discute sobre si se puede matar a la propia madre no merece argumentos sino azotes.',
    'Es preciso que la filosofía sea un saber especial, de los primeros principios y de las primeras causas.',
    'No hay que empezar siempre por la noción primera de las cosas que se estudian, sino por aquello que puede facilitar el aprendizaje.',
    'No todo término merece el nombre de fin, sino tan sólo el que es óptimo.',
    'El estudio es amargo, pero su fruto es dulce.',
    'Las revoluciones no se hacen por menudencias, pero nacen por menudencias.',
    'Lo que tiene alma se distingue de lo que no la tiene por el hecho de vivir.',
    'Es preciso preferir la soberanía de la ley a la de uno de los ciudadanos.',
    'Si las acciones humanas pueden ser nobles, vergonzosas o indiferentes, lo mismo ocurre con los placeres correspondientes. Hay placeres que derivan de actividades nobles, y otros de vergonzoso origen.',
    'Las cosas se llaman equívocas cuando tan sólo tienen de común el nombre.',
    'Los tiranos se rodean de hombres malos porque les gusta ser adulados y ningún hombre de espíritu elevado les adulará.',
    'El ser inmóvil mueve como objeto del amor, y lo que él mueve imprime el movimiento a todo lo demás.',
    'El fin de la ciencia especulativa es la verdad, y el fin de la ciencia práctica es la acción.',
    'Demasiado poco valor es cobardía y demasiado valor es temeridad.',
    'No hace falta un gobierno perfecto; se necesita uno que sea práctico.',
    'La necesidad ha hecho aparearse a quienes no pueden existir el uno sin el otro, como son el varón y la mujer.',
    'Solamente haciendo el bien se puede realmente ser feliz.',
    'La belleza del hombre está o en la sonoridad, o en el significado.',
    'El género humano tiene, para saber conducirse, el arte y el razonamiento.',
    'La virtud está en el punto medio',
    'No hay genio sin un gramo de locura.',
    'La bestialidad es un mal menor que la perversidad, pero es más temible.',
    'Lo mejor es salir de la vida como de una fiesta, ni sediento, ni bebido.',
    'Si tanto me alaban, será por alabarse a sí mismos, pues al alabarme dan a entender que me comprenden.',
    'Es evidente que todos los fines no son fines perfectos. Pero el bien supremo constituye, de alguna manera, un fin perfecto.',
    'La poesía es más profunda y filosófica que la historia.',
    'Si el espíritu es un atributo divino, una existencia conforme al espíritu será verdaderamente divina.',
    'Todos los aduladores son mercenarios, y todos los hombres de bajo espíritu son aduladores.',
    'No hay que prestar atención a quienes nos aconsejan, so pretexto de que somos hombres, no pensar más que en las cosas humanas y, so pretexto de que somos mortales, renunciar a las cosas inmortales.',
    'Todos o casi todos distinguen el alma por tres de sus atributos: el movimiento, la sensación y la incorporeidad.']


def generate_quote() -> str:
    random_quote = choice(aristotle_quotes)
    return random_quote
